### ISSUE TITLE
No module named 'diamond_miner.generator'

### ISSUE THREAD

**Issue by Virginia2244** [dioptra-io/diamond-miner#63]
I am trying to get your sample code from the [documentation](https://dioptra-io.github.io/diamond-miner/workflow.html) up and running but my computer is running into issues finding `diamond_miner.generator`, `diamond_miner.rounds.mda`, and `pycaracal`. I am running on Linux, I have python 3.8, and I have run `pip install diamond-miner`. What other steps need to be taken in order to get this code to run?

**Comment by christopolise** [comment]
I think this is the link for the documentation:
https://dioptra-io.github.io/diamond-miner/workflow.html

**Comment by maxmouchet** [comment]
Hi,

Thanks for your feedback, the documentation was indeed not up-to-date.
It should be OK now. Let me know if this works for you!
